set nocompatible
syntax enable
filetype plugin on
set path+=**
set wildignore+=**/node_modules/**
set wildmenu
set ts=4
set shiftwidth=4
set relativenumber

let g:netrw_altv=1
let g:netrw_alto=1

set splitbelow
set splitright

"set Formatters
au FileType xml setlocal equalprg=xmllint\ --format\ --recover\ -\ 2>/dev/null
au FileType javascript setlocal equalprg=js-beautify

